### PR TITLE
Print error gif in case of failures

### PR DESCRIPTION
**Pull request by briancain**

### CODE REVIEW

**Comment by briancain** [comment]
@passy I was trying to test this, but I'm unsure on how to get it to error so I can see the output and make sure it looks right...ideas?

**Comment by passy** [comment]
That GIF is phenomenal. The easiest way to provoke a failure is to disconnect the WiFi. I wonder, though, if it would be nicer to render it inline (unless the preview is disabled). What do you think?

**Comment by briancain** [comment]
@passy ah yeah! Works like I expected:

```
brian@yocalhost:givegif % ~/.local/bin/givegif test                                                                                                                                               ±[error-gifz]
http://i.giphy.com/U66k57wdrSfAI.gif
Error: ConnectionError {connectionError = FailedConnectionException2 "api.giphy.com" 443 True getAddrInfo: does not exist (nodename nor servname provided, or not known)}
```

Do you have an example of what you mean by rendering it inline?

**Comment by briancain** [comment]
@passy oh, do inline gifs only get rendered if they're the last thing printed? I could move the gif to print after the error message. I'm not testing this on a version of iterm that supports inline gifs.

**Comment by passy** [comment]
I think that without rendering it, it's more confusing than helpful. On the first time, you don't know what this means and once you've opened it manually once you're probably unlikely to do it again - and a URL itself is far less funny than the image behind it. :)

I fear inline-printing the image will require some deeper changes to the image renderer.

**Comment by briancain** [comment]
Ah! I see what you mean, I'd basically have to use this to render the image inline?

https://github.com/passy/givegif/blob/master/app/Main.hs#L118-L123

That does seem trickier...heh.

**Comment by jeffweiss** [comment]
@briancain you may want to look at 
screen shot 2016-04-13 at 2 45 04 pm

from the [iterm docs](https://www.iterm2.com/images.html)

**Comment by passy** [comment]
@jeffweiss This is already implemented. :)

@briancain Yes, exactly.

**Comment by briancain** [comment]
@passy Cool. Well I'd still love to try that. I'll find some time soon and attempt that (and in the process learn more haskell :D)

**Comment by briancain** [comment]
Closing this, as I haven't found the time to pick it up :(

**Pull request closed without merging**
